name: drinking-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.0
  - pip:
    - flask==3.1.0
    - flask-cors==5.0.1
    - pymongo==4.6.2
    - azure-storage-blob==12.25.1
    - azure-identity==1.21.0
    - openai==1.14.0
    - python-dotenv==1.1.0
    - gunicorn==21.2.0
    - langchain==0.1.0
    - pydantic==1.10.13
    - langchain-core==0.2.0
    - langgraph==0.1.16
    - langchain-openai==0.0.5
    - langsmith==0.1.5